/* eslint-disable @typescript-eslint/no-require-imports */
import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  plugins: [
    require("@tailwindcss/typography"),
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#ffb59f",
        background: "#faf8ff",
        "secondary-fixed-dim": "#c8c6c5",
        "primary-soft": "#c9e0fc",
        "primary-bright": "#296ef9",
        steel: "#c2c2c2",
        error: "#ba1a1a",
        "primary-deep": "#0e3191",
        "on-primary-fixed": "#00164f",
        "on-surface-variant": "#434655",
        "on-secondary-fixed-variant": "#474746",
        "on-tertiary-fixed": "#3a0a00",
        "surface-container-high": "#e7e7f3",
        "surface-bright": "#faf8ff",
        "on-primary-fixed-variant": "#003bb0",
        "on-ink": "#ffffff",
        "inverse-primary": "#b6c4ff",
        primary: "#0036a4",
        "on-primary-container": "#c2ceff",
        "primary-fixed-dim": "#b6c4ff",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#862300",
        "bloom-coral": "#ff5050",
        "storm-sea": "#7fadbe",
        "surface-container": "#ededf9",
        "on-tertiary-container": "#ffc1b0",
        "surface-container-low": "#f3f2ff",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#1c1b1b",
        charcoal: "#3d3d3d",
        "tertiary-fixed": "#ffdbd1",
        "on-background": "#191b23",
        "surface-container-highest": "#e2e1ed",
        "bloom-rose": "#f9d4d2",
        "on-primary": "#ffffff",
        graphite: "#636363",
        "inverse-surface": "#2e3039",
        "primary-container": "#024ad8",
        "on-secondary-container": "#636262",
        "secondary-fixed": "#e5e2e1",
        surface: "#faf8ff",
        "primary-fixed": "#dce1ff",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "secondary-container": "#e2dfde",
        "on-surface": "#191b23",
        "tertiary-container": "#a52d00",
        "inverse-on-surface": "#f0f0fc",
        ink: "#1a1a1a",
        "storm-deep": "#356373",
        "surface-tint": "#1451de",
        "surface-variant": "#e2e1ed",
        outline: "#747686",
        "bloom-deep": "#b3262b",
        "on-error-container": "#93000a",
        "ink-deep": "#000000",
        canvas: "#ffffff",
        "outline-variant": "#c3c5d7",
        secondary: "#5f5e5e",
        fog: "#e8e8e8",
        tertiary: "#7c2000",
        "on-error": "#ffffff",
        "surface-dim": "#d9d9e5",
        paper: "#ffffff",
        cloud: "#f7f7f7",
        "ink-soft": "#292929",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        section: "80px",
        xs: "8px",
        xxs: "4px",
        xxl: "32px",
        "max-width": "1366px",
        sm: "12px",
        md: "16px",
        xl: "24px",
        lg: "20px",
      },
      fontFamily: {
        "caption-bold": ["Manrope"],
        "body-md": ["Manrope"],
        "display-sm": ["Manrope"],
        "display-lg": ["Manrope"],
        "display-xs": ["Manrope"],
        "button-md": ["Manrope"],
        "body-lg": ["Manrope"],
        "body-emphasis": ["Manrope"],
        "display-xxl": ["Manrope"],
        "display-md": ["Manrope"],
        "price-md": ["Manrope"],
        "caption-md": ["Manrope"],
        "display-xl": ["Manrope"],
        "caption-sm": ["Manrope"],
      },
      fontSize: {
        "caption-bold": [
          "14px",
          { lineHeight: "1.3", letterSpacing: "0", fontWeight: "700" },
        ],
        "body-md": [
          "16px",
          { lineHeight: "1.38", letterSpacing: "0", fontWeight: "400" },
        ],
        "display-sm": [
          "24px",
          { lineHeight: "1.17", letterSpacing: "0", fontWeight: "500" },
        ],
        "display-lg": [
          "44px",
          { lineHeight: "1.0", letterSpacing: "0", fontWeight: "500" },
        ],
        "display-xs": [
          "20px",
          { lineHeight: "1.0", letterSpacing: "0", fontWeight: "500" },
        ],
        "button-md": [
          "14px",
          { lineHeight: "1.4", letterSpacing: "0.7px", fontWeight: "600" },
        ],
        "body-lg": [
          "18px",
          { lineHeight: "1.33", letterSpacing: "0", fontWeight: "400" },
        ],
        "body-emphasis": [
          "16px",
          { lineHeight: "1.38", letterSpacing: "0", fontWeight: "500" },
        ],
        "display-xxl": [
          "72px",
          { lineHeight: "1.0", letterSpacing: "0", fontWeight: "500" },
        ],
        "display-md": [
          "32px",
          { lineHeight: "1.0", letterSpacing: "0", fontWeight: "500" },
        ],
        "price-md": [
          "24px",
          { lineHeight: "1.17", letterSpacing: "0", fontWeight: "500" },
        ],
        "caption-md": [
          "14px",
          { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" },
        ],
        "display-xl": [
          "56px",
          { lineHeight: "1.0", letterSpacing: "0", fontWeight: "500" },
        ],
        "caption-sm": [
          "12px",
          { lineHeight: "1.33", letterSpacing: "0", fontWeight: "400" },
        ],
      },
    },
  },
};
export default config;
